# Generated by Django 4.2 on 2023-05-04 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stocks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell")],
                        max_length=4,
                        verbose_name="Тип сделки",
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[("STOCK", "Stock")],
                        max_length=10,
                        verbose_name="Тип актива",
                    ),
                ),
                (
                    "date",
                    models.CharField(max_length=10, verbose_name="Дата транзакции"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Цена сделки"
                    ),
                ),
                (
                    "fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        null=True,
                        verbose_name="Комиссия за сделку",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="Количество")),
                (
                    "ticker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stocks.stock",
                        verbose_name="Акция",
                    ),
                ),
            ],
            options={
                "verbose_name": "Транзакция",
                "verbose_name_plural": "Транзакции",
                "ordering": ["creation_date", "ticker", "user"],
            },
        ),
    ]
