# Generated by Django 4.2 on 2023-10-30 18:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stocks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell")],
                        max_length=4,
                        validators=[django.core.validators.MinLengthValidator(1)],
                        verbose_name="Transaction type",
                    ),
                ),
                (
                    "date",
                    models.DateField(max_length=10, verbose_name="Transaction date"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Transaction price"
                    ),
                ),
                (
                    "fee",
                    models.DecimalField(
                        decimal_places=2,
                        default="0.00",
                        max_digits=8,
                        null=True,
                        verbose_name="Transaction fee",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="Transaction quantity")),
                (
                    "ticker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stocks.asset",
                        verbose_name="Asset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Транзакция",
                "verbose_name_plural": "Транзакции",
                "ordering": ["creation_date", "ticker", "user"],
            },
        ),
    ]
