# Generated by Django 4.2 on 2023-11-12 08:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="accrued_interest",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=8,
                null=True,
                verbose_name="Accrued Interest",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="fee",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=8,
                null=True,
                verbose_name="Transaction fee",
            ),
        ),
    ]
