# Generated by Django 4.2 on 2023-06-14 18:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stocks", "0004_alter_prodcalendar_date"),
        ("transactions", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="asset_type",
            field=models.CharField(
                choices=[("STOCK", "Stock")],
                max_length=10,
                validators=[django.core.validators.MinLengthValidator(1)],
                verbose_name="Asset type",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="creation_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creation date"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateField(max_length=10, verbose_name="Transaction date"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="fee",
            field=models.DecimalField(
                decimal_places=2,
                default="0.00",
                max_digits=8,
                null=True,
                verbose_name="Transaction fee",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=8, verbose_name="Transaction price"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="quantity",
            field=models.IntegerField(verbose_name="Transaction quantity"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="ticker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="stocks.stock",
                verbose_name="Share",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("BUY", "Buy"), ("SELL", "Sell")],
                max_length=4,
                validators=[django.core.validators.MinLengthValidator(1)],
                verbose_name="Transaction type",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Transaction user",
            ),
        ),
    ]
