# Generated by Django 4.2 on 2023-10-28 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0003_alter_transaction_ticker"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="asset_type",
        ),
    ]
