# Generated by Django 4.2 on 2023-10-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CurrencyRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tradedate", models.DateField()),
                (
                    "price_usd",
                    models.DecimalField(decimal_places=4, max_digits=8, null=True),
                ),
                ("is_closed", models.BooleanField()),
                ("update_time", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
