# Generated by Django 4.2 on 2023-05-04 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProdCalendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.CharField(max_length=10, verbose_name="Дата")),
                (
                    "date_status",
                    models.CharField(
                        choices=[("0", "Working"), ("1", "Nonworking")],
                        max_length=10,
                        verbose_name="Статус дня",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "date_status"],
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "asset_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="assets.asset",
                    ),
                ),
                (
                    "ticker",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Тикер акции"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя акции")),
                (
                    "isin",
                    models.CharField(
                        blank=True, max_length=100, unique=True, verbose_name="ISIN"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Валюта номинала"
                    ),
                ),
                (
                    "issuedate",
                    models.DateField(blank=True, verbose_name="Дата начала торгов"),
                ),
                (
                    "latname",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Английское наименование",
                    ),
                ),
                (
                    "isqualifiedinvestors",
                    models.BooleanField(
                        blank=True,
                        verbose_name="Бумаги для квалифицированных инвесторов",
                    ),
                ),
                (
                    "morningsession",
                    models.BooleanField(
                        blank=True,
                        verbose_name="Допуск к утренней дополнительной торговой сессии",
                    ),
                ),
                (
                    "eveningsession",
                    models.BooleanField(
                        blank=True,
                        verbose_name="Допуск к вечерней дополнительной торговой сессии",
                    ),
                ),
                (
                    "typename",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Вид/категория ценной бумаги",
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Код типа инструмента"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Тип бумаги"
                    ),
                ),
                (
                    "groupname",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Тип инструмента"
                    ),
                ),
                ("stock_data", models.JSONField(verbose_name="Данные об акции")),
                (
                    "latest_dividend_update",
                    models.DateField(
                        blank=True,
                        verbose_name="Дата последнего обновления информации о дивидендах",
                    ),
                ),
            ],
            options={
                "verbose_name": "Акция",
                "verbose_name_plural": "Акции",
                "ordering": ["creation_date", "ticker", "name"],
            },
            bases=("assets.asset",),
        ),
        migrations.CreateModel(
            name="StocksOfUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stocks.stock"
                    ),
                ),
            ],
            options={
                "verbose_name": "Акции пользователя",
                "verbose_name_plural": "Акции пользователей",
                "ordering": ["stock"],
            },
        ),
    ]
