# Generated by Django 4.1.4 on 2023-01-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('ticker', models.CharField(max_length=10, unique=True, verbose_name='Тикер акции')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Имя акции')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
                'ordering': ['creation_date', 'ticker', 'name'],
            },
        ),
    ]
