# Generated by Django 4.2 on 2023-05-04 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stocks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocksofuser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                related_name="stock",
                through="stocks.StocksOfUser",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
