# Generated by Django 4.1.4 on 2023-01-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя акции'),
        ),
    ]
