# Generated by Django 4.2 on 2023-05-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="latest_dividend_update",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Дата последнего обновления информации о дивидендах",
            ),
        ),
    ]
