# Generated by Django 4.1.4 on 2023-03-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_prodcalendar_alter_stock_stock_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prodcalendar',
            options={'ordering': ['date', 'date_status']},
        ),
        migrations.AddField(
            model_name='stock',
            name='currency',
            field=models.CharField(blank=True, max_length=10, verbose_name='Валюта номинала'),
        ),
        migrations.AddField(
            model_name='stock',
            name='eveningsession',
            field=models.CharField(blank=True, max_length=1, verbose_name='Допуск к вечерней дополнительной торговой сессии'),
        ),
        migrations.AddField(
            model_name='stock',
            name='group',
            field=models.CharField(blank=True, max_length=100, verbose_name='Код типа инструмента'),
        ),
        migrations.AddField(
            model_name='stock',
            name='groupname',
            field=models.CharField(blank=True, max_length=100, verbose_name='Тип инструмента'),
        ),
        migrations.AddField(
            model_name='stock',
            name='isin',
            field=models.CharField(blank=True, max_length=100, verbose_name='ISIN'),
        ),
        migrations.AddField(
            model_name='stock',
            name='isqualifiedinvestors',
            field=models.CharField(blank=True, max_length=1, verbose_name='Бумаги для квалифицированных инвесторов'),
        ),
        migrations.AddField(
            model_name='stock',
            name='latname',
            field=models.CharField(blank=True, max_length=100, verbose_name='Английское наименование'),
        ),
        migrations.AddField(
            model_name='stock',
            name='morningsession',
            field=models.CharField(blank=True, max_length=1, verbose_name='Допуск к утренней дополнительной торговой сессии'),
        ),
        migrations.AddField(
            model_name='stock',
            name='type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Тип бумаги'),
        ),
        migrations.AddField(
            model_name='stock',
            name='typename',
            field=models.CharField(blank=True, max_length=100, verbose_name='Вид/категория ценной бумаги'),
        ),
    ]
