# Generated by Django 4.2 on 2023-10-28 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetsHistoricalData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tradedate", models.DateField()),
                ("numtrades", models.IntegerField(null=True)),
                (
                    "value",
                    models.DecimalField(decimal_places=2, max_digits=15, null=True),
                ),
                (
                    "open",
                    models.DecimalField(decimal_places=5, max_digits=13, null=True),
                ),
                (
                    "low",
                    models.DecimalField(decimal_places=5, max_digits=13, null=True),
                ),
                (
                    "high",
                    models.DecimalField(decimal_places=5, max_digits=13, null=True),
                ),
                (
                    "legalcloseprice",
                    models.DecimalField(decimal_places=5, max_digits=13),
                ),
                (
                    "waprice",
                    models.DecimalField(decimal_places=5, max_digits=13, null=True),
                ),
                (
                    "close",
                    models.DecimalField(decimal_places=5, max_digits=13, null=True),
                ),
                ("volume", models.IntegerField(null=True)),
                (
                    "waval",
                    models.DecimalField(decimal_places=5, max_digits=13, null=True),
                ),
                (
                    "trendclspr",
                    models.DecimalField(decimal_places=3, max_digits=7, null=True),
                ),
                (
                    "couponpercent",
                    models.DecimalField(decimal_places=5, max_digits=13, null=True),
                ),
                (
                    "couponvalue",
                    models.DecimalField(decimal_places=5, max_digits=13, null=True),
                ),
                (
                    "yieldclose",
                    models.DecimalField(decimal_places=5, max_digits=13, null=True),
                ),
                ("is_closed", models.BooleanField()),
                ("update_time", models.DateTimeField(blank=True, null=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stocks.asset"
                    ),
                ),
            ],
            options={
                "unique_together": {("asset", "tradedate")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="shareshistoricaldata",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="shareshistoricaldata",
            name="share",
        ),
        migrations.DeleteModel(
            name="BondsHistoricalData",
        ),
        migrations.DeleteModel(
            name="SharesHistoricalData",
        ),
    ]
