# Generated by Django 4.2 on 2023-10-30 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bond",
            name="couponpercent",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=10,
                null=True,
                verbose_name="Текущий процент",
            ),
        ),
        migrations.AlterField(
            model_name="bond",
            name="couponvalue",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=10,
                null=True,
                verbose_name="Текущий купон",
            ),
        ),
        migrations.AlterField(
            model_name="bond",
            name="days_to_redemption",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Дней до погашения"
            ),
        ),
    ]
