# Generated by Django 4.2 on 2023-06-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0003_alter_stock_latest_dividend_update"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prodcalendar",
            name="date",
            field=models.DateField(max_length=10, verbose_name="Дата"),
        ),
    ]
