# Generated by Django 4.1.4 on 2023-03-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_alter_prodcalendar_options_stock_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='issuedate',
            field=models.CharField(blank=True, max_length=10, verbose_name='Дата начала торгов'),
        ),
    ]
