# Generated by Django 4.2 on 2023-11-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0003_alter_bond_couponpercent_alter_bond_couponvalue_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bond",
            name="face_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=10,
                null=True,
                verbose_name="Номинал",
            ),
        ),
    ]
