# Generated by Django 4.2 on 2023-09-24 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0004_alter_prodcalendar_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="SharesHistoricalData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tradedate", models.DateField()),
                ("numtrades", models.IntegerField()),
                ("value", models.DecimalField(decimal_places=2, max_digits=15)),
                ("open", models.DecimalField(decimal_places=5, max_digits=13)),
                ("low", models.DecimalField(decimal_places=5, max_digits=13)),
                ("high", models.DecimalField(decimal_places=5, max_digits=13)),
                (
                    "legalcloseprice",
                    models.DecimalField(decimal_places=5, max_digits=13),
                ),
                ("warprice", models.DecimalField(decimal_places=5, max_digits=13)),
                ("close", models.DecimalField(decimal_places=5, max_digits=13)),
                ("volume", models.IntegerField()),
                ("waval", models.DecimalField(decimal_places=5, max_digits=13)),
                ("trendclspr", models.DecimalField(decimal_places=3, max_digits=7)),
                ("is_closed", models.BooleanField()),
                ("update_time", models.DateTimeField(blank=True)),
                (
                    "share",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stocks.stock"
                    ),
                ),
            ],
            options={
                "unique_together": {("share", "tradedate")},
            },
        ),
    ]
