# Generated by Django 4.2 on 2023-09-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0005_shareshistoricaldata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shareshistoricaldata",
            name="warprice",
            field=models.DecimalField(decimal_places=5, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name="shareshistoricaldata",
            name="waval",
            field=models.DecimalField(decimal_places=5, max_digits=13, null=True),
        ),
    ]
