# Generated by Django 4.2 on 2023-11-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0006_asset_primary_boardid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="creation_date",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Дата создания"
            ),
        ),
    ]
