# Generated by Django 4.2 on 2023-09-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0006_alter_shareshistoricaldata_warprice_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shareshistoricaldata",
            name="trendclspr",
            field=models.DecimalField(decimal_places=3, max_digits=7, null=True),
        ),
    ]
