# Generated by Django 4.2 on 2023-09-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0007_alter_shareshistoricaldata_trendclspr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shareshistoricaldata",
            name="update_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
