# Generated by Django 4.2 on 2023-09-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0008_alter_shareshistoricaldata_update_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shareshistoricaldata",
            name="close",
            field=models.DecimalField(decimal_places=5, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name="shareshistoricaldata",
            name="high",
            field=models.DecimalField(decimal_places=5, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name="shareshistoricaldata",
            name="low",
            field=models.DecimalField(decimal_places=5, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name="shareshistoricaldata",
            name="open",
            field=models.DecimalField(decimal_places=5, max_digits=13, null=True),
        ),
    ]
