# Generated by Django 4.2 on 2023-09-24 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0009_alter_shareshistoricaldata_close_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shareshistoricaldata",
            old_name="warprice",
            new_name="waprice",
        ),
    ]
