# Generated by Django 4.2 on 2023-11-22 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_fields_to_display_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stocks", "0009_currencyrate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dividend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                ("date", models.DateField(verbose_name="Dividend date")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        verbose_name="Dividend amount for one share",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stocks.asset"
                    ),
                ),
            ],
            options={
                "verbose_name": "Дивиденд",
                "verbose_name_plural": "Дивиденды",
                "ordering": ["creation_date", "asset", "amount"],
            },
        ),
        migrations.CreateModel(
            name="DividendsOfUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_received",
                    models.BooleanField(
                        default=False,
                        help_text="shows if user got dividend",
                        verbose_name="Dividend status",
                    ),
                ),
                (
                    "dividend",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stocks.dividend",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Дивиденд пользователя",
                "verbose_name_plural": "Дивиденды пользователей",
                "ordering": ["dividend"],
                "unique_together": {("user", "dividend")},
            },
        ),
        migrations.AddField(
            model_name="dividend",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                related_name="dividend",
                through="stocks.DividendsOfUser",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="DividendsOfPortfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_received",
                    models.BooleanField(
                        default=False,
                        help_text="shows if portfolio got dividend",
                        verbose_name="Dividend status",
                    ),
                ),
                (
                    "dividend",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stocks.dividend",
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.portfolio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Дивиденд портфеля",
                "verbose_name_plural": "Дивиденды портфеля",
                "ordering": ["dividend"],
                "unique_together": {("portfolio", "dividend")},
            },
        ),
    ]
