# Generated by Django 4.2 on 2023-09-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0010_rename_warprice_shareshistoricaldata_waprice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shareshistoricaldata",
            name="numtrades",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="shareshistoricaldata",
            name="value",
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name="shareshistoricaldata",
            name="volume",
            field=models.IntegerField(null=True),
        ),
    ]
