# Generated by Django 4.2 on 2023-11-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_fields_to_display_and_more"),
        ("stocks", "0011_transaction"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DividendsOfPortfolio",
            new_name="AccrualsOfPortfolio",
        ),
        migrations.RemoveField(
            model_name="dividend",
            name="users",
        ),
        migrations.AddField(
            model_name="dividend",
            name="portfolios",
            field=models.ManyToManyField(
                blank=True,
                related_name="dividend",
                through="stocks.AccrualsOfPortfolio",
                to="users.portfolio",
            ),
        ),
        migrations.DeleteModel(
            name="DividendsOfUser",
        ),
    ]
