# Generated by Django 4.2 on 2023-10-25 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0004_asset_portfolios"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stocks", "0011_alter_shareshistoricaldata_numtrades_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bond",
            fields=[
                (
                    "asset_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="assets.asset",
                    ),
                ),
                (
                    "secid",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="ID инструмента"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя акции")),
                (
                    "isin",
                    models.CharField(
                        blank=True, max_length=100, unique=True, verbose_name="ISIN"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Валюта номинала"
                    ),
                ),
                (
                    "issuedate",
                    models.DateField(blank=True, verbose_name="Дата начала торгов"),
                ),
                (
                    "startdatemoex",
                    models.DateField(
                        blank=True, verbose_name="Дата начала торгов на MOEX"
                    ),
                ),
                (
                    "buybackdate",
                    models.DateField(blank=True, verbose_name="Дата байбека"),
                ),
                (
                    "matdate",
                    models.DateField(blank=True, verbose_name="Дата погашения"),
                ),
                (
                    "couponpercent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        verbose_name="Текущий процент",
                    ),
                ),
                (
                    "couponvalue",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        verbose_name="Текущий купон",
                    ),
                ),
                (
                    "days_to_redemption",
                    models.IntegerField(blank=True, verbose_name="Дней до погашения"),
                ),
                (
                    "latname",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Английское наименование",
                    ),
                ),
                (
                    "isqualifiedinvestors",
                    models.BooleanField(
                        blank=True,
                        verbose_name="Бумаги для квалифицированных инвесторов",
                    ),
                ),
                (
                    "morningsession",
                    models.BooleanField(
                        blank=True,
                        verbose_name="Допуск к утренней дополнительной торговой сессии",
                    ),
                ),
                (
                    "eveningsession",
                    models.BooleanField(
                        blank=True,
                        verbose_name="Допуск к вечерней дополнительной торговой сессии",
                    ),
                ),
                (
                    "typename",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Вид/категория ценной бумаги",
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Код типа инструмента"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Тип бумаги"
                    ),
                ),
                (
                    "groupname",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Тип инструмента"
                    ),
                ),
                (
                    "latest_coupon_update",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Дата последнего обновления информации о купонах",
                    ),
                ),
            ],
            options={
                "verbose_name": "Облигация",
                "verbose_name_plural": "Облигации",
                "ordering": ["creation_date", "secid", "name"],
            },
            bases=("assets.asset",),
        ),
        migrations.CreateModel(
            name="BondOfUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bond",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stocks.bond"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Облигации пользователя",
                "verbose_name_plural": "Облигации пользователей",
                "ordering": ["bond"],
            },
        ),
        migrations.AddField(
            model_name="bond",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                related_name="bond",
                through="stocks.BondOfUser",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
