# Generated by Django 4.2 on 2023-10-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0012_bond_bondofuser_bond_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bond",
            name="secid",
            field=models.CharField(
                max_length=20, unique=True, verbose_name="ID инструмента"
            ),
        ),
    ]
