# Generated by Django 4.2 on 2023-10-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0013_alter_bond_secid"),
    ]

    operations = [
        migrations.AddField(
            model_name="bond",
            name="couponfrequency",
            field=models.IntegerField(
                blank=True, default=2, verbose_name="Частота выплаты купона в год"
            ),
            preserve_default=False,
        ),
    ]
