# Generated by Django 4.2 on 2023-12-24 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0013_alter_accrualsofportfolio_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stocksofuser",
            name="stock",
        ),
        migrations.RemoveField(
            model_name="stocksofuser",
            name="user",
        ),
        migrations.RemoveField(
            model_name="bond",
            name="latest_coupon_update",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="latest_dividend_update",
        ),
        migrations.DeleteModel(
            name="BondOfUser",
        ),
        migrations.DeleteModel(
            name="StocksOfUser",
        ),
    ]
