# Generated by Django 4.2 on 2023-10-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0014_bond_couponfrequency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bond",
            name="buybackdate",
            field=models.DateField(blank=True, null=True, verbose_name="Дата байбека"),
        ),
    ]
