# Generated by Django 4.2 on 2023-12-24 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0014_remove_stocksofuser_stock_remove_stocksofuser_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asset",
            name="users",
        ),
        migrations.DeleteModel(
            name="AssetsOfUser",
        ),
    ]
