# Generated by Django 4.2 on 2023-12-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0015_remove_asset_users_delete_assetsofuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="currencyrate",
            name="price_euro",
            field=models.DecimalField(decimal_places=4, max_digits=8, null=True),
        ),
    ]
