# Generated by Django 4.2 on 2023-12-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0016_currencyrate_price_euro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currencyrate",
            name="is_closed",
            field=models.BooleanField(
                verbose_name="Shows if date is closed and can not be updated"
            ),
        ),
        migrations.AlterField(
            model_name="currencyrate",
            name="price_euro",
            field=models.DecimalField(
                decimal_places=4,
                max_digits=8,
                null=True,
                verbose_name="CBR usd rate for the date",
            ),
        ),
        migrations.AlterField(
            model_name="currencyrate",
            name="price_usd",
            field=models.DecimalField(
                decimal_places=4,
                max_digits=8,
                null=True,
                verbose_name="CBR usd rate for the date",
            ),
        ),
        migrations.AlterField(
            model_name="currencyrate",
            name="tradedate",
            field=models.DateField(verbose_name="The date of the rate data"),
        ),
        migrations.AlterField(
            model_name="currencyrate",
            name="update_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Last update time"
            ),
        ),
    ]
