# Generated by Django 4.2 on 2023-04-25 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stocks", "0004_stock_issuedate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dividend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "date",
                    models.CharField(max_length=10, verbose_name="Дата дивиденда"),
                ),
                (
                    "dividend",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        verbose_name="Размер дивиденда на акцию",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stocks.stock",
                    ),
                ),
            ],
            options={
                "verbose_name": "Дивиденд",
                "verbose_name_plural": "Дивиденды",
                "ordering": ["creation_date", "stock", "dividend"],
            },
        ),
    ]
