# Generated by Django 4.2 on 2023-10-26 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dividend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                ("date", models.DateField(verbose_name="Dividend date")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        verbose_name="Dividend amount for one share",
                    ),
                ),
            ],
            options={
                "verbose_name": "Дивиденд",
                "verbose_name_plural": "Дивиденды",
                "ordering": ["creation_date", "stock", "amount"],
            },
        ),
        migrations.CreateModel(
            name="DividendsOfUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_received",
                    models.BooleanField(
                        default=False,
                        help_text="shows if user got dividend",
                        verbose_name="Dividend status",
                    ),
                ),
                (
                    "dividend",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dividends.dividend",
                    ),
                ),
            ],
            options={
                "verbose_name": "Дивиденд пользователя",
                "verbose_name_plural": "Дивиденды пользователей",
                "ordering": ["dividend"],
            },
        ),
    ]
