# Generated by Django 4.2 on 2023-10-30 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stocks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dividends", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dividendsofuser",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dividend",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="stocks.asset"
            ),
        ),
        migrations.AddField(
            model_name="dividend",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                related_name="dividend",
                through="dividends.DividendsOfUser",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dividendsofuser",
            unique_together={("user", "dividend")},
        ),
    ]
