# Generated by Django 4.2 on 2023-05-06 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dividends", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dividendsofuser",
            old_name="status",
            new_name="is_received",
        ),
    ]
