# Generated by Django 4.2 on 2023-11-05 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        ("dividends", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DividendsOfPortfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_received",
                    models.BooleanField(
                        default=False,
                        help_text="shows if portfolio got dividend",
                        verbose_name="Dividend status",
                    ),
                ),
                (
                    "dividend",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dividends.dividend",
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.portfolio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Дивиденд портфеля",
                "verbose_name_plural": "Дивиденды портфеля",
                "ordering": ["dividend"],
                "unique_together": {("portfolio", "dividend")},
            },
        ),
    ]
