# Generated by Django 4.2 on 2023-05-30 19:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dividends", "0003_rename_status_dividendsofuser_is_received"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dividend",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=8,
                verbose_name="Dividend amount for one share",
            ),
        ),
        migrations.AlterField(
            model_name="dividend",
            name="creation_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creation date"),
        ),
        migrations.AlterField(
            model_name="dividend",
            name="date",
            field=models.DateField(verbose_name="Dividend date"),
        ),
        migrations.AlterField(
            model_name="dividendsofuser",
            name="is_received",
            field=models.BooleanField(
                default=False,
                help_text="shows if user got dividend",
                verbose_name="Dividend status",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dividendsofuser",
            unique_together={("user", "dividend")},
        ),
    ]
