# Generated by Django 4.1.4 on 2023-01-05 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_alter_stock_name'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersStocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stocks.stock')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Акция пользователя',
                'verbose_name_plural': 'Акции пользователей',
                'ordering': ['stock'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='stocks',
            field=models.ManyToManyField(blank=True, related_name='users', through='users.UsersStocks', to='stocks.stock'),
        ),
    ]
