# Generated by Django 4.2 on 2023-09-16 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="fields_to_display",
            field=models.JSONField(
                default='{"ticker": true, "name": true, "currency": true, "quantity": true, "purchase_price": true, "current_price": true, "dividends_received": true, "money_result_without_divs": true, "money_result_with_divs": true, "percent_result": true, "rate_of_return": true}',
                verbose_name="Поля для отображения",
            ),
        ),
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation_date"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Portfolio name"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Portfolio owner",
                    ),
                ),
            ],
        ),
    ]
