# Generated by Django 4.1.4 on 2023-04-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fields_to_display',
            field=models.JSONField(blank=True, null=True, verbose_name='Поля для отображения'),
        ),
    ]
