# Generated by Django 4.2 on 2023-09-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_fields_to_display_portfolio"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="is_current",
            field=models.BooleanField(
                default=True,
                verbose_name="If the portfolio is current for the owner. The current portfolio is used to work with transactions",
            ),
            preserve_default=False,
        ),
    ]
