# Generated by Django 4.2 on 2023-05-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("stocks", "stocks"),
                            ("bonds", "bonds"),
                            ("currencies", "currencies"),
                            ("fonds", "fonds"),
                        ],
                        max_length=20,
                        verbose_name="Тип актива",
                    ),
                ),
            ],
        ),
    ]
