# Generated by Django 4.2 on 2023-09-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="asset_type",
            field=models.CharField(
                choices=[
                    ("stocks", "stocks"),
                    ("bonds", "bonds"),
                    ("currencies", "currencies"),
                    ("funds", "funds"),
                ],
                max_length=20,
                verbose_name="Тип актива",
            ),
        ),
    ]
