# Generated by Django 4.2 on 2023-09-16 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_portfolio_is_current"),
        ("assets", "0002_alter_asset_asset_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetOfPortfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="assets.asset"
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.portfolio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Объекты портфеля",
                "verbose_name_plural": "Объекты портфеля",
                "ordering": ["portfolio"],
            },
        ),
    ]
